### ISSUE TITLE
More Mods to Add

### ISSUE THREAD

**Issue by vylryna** [Kashiiera/Minecraft-Wii-U-Mod-Injector#2]
Here's some more mods that my private injector has :)

**Take Everything Anywhere**
Address: 0x02DEC0B4
Value: 0x38600001
Origin: 0x57E3063E

**View Armour on Side**
Address: 0x02E9B1B0
Value: 0x7FE4FB78
Origin: 0x7FC4F378

 **Slow-Motion**
Address: 0x109473C8
Value: 0x3F700000
Origin: 0x3FF00000

**Comment by Kashiiera** [comment]
Added, these will be added in v5.1.3 with credit as always.
